// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/about": StaticRoute;
    "/contact": StaticRoute;
    "/": StaticRoute;
    "/portfolio": StaticRoute;
    "/portfolio/[slug]": StaticRoute;
    "/products": StaticRoute;
    "/services": StaticRoute;
  }
}
